language: ruby
cache:
  directories:
  - bundle
rvm:
- 2.4.1
bundler_args: "--without documentation --path bundle"
before_install:
- git fetch --depth=1
- gem install bundler
- mkdir -p tmp && wget --no-check-certificate https://binaries.rightscale.com/rsbin/rsc/v8/rsc-linux-amd64.tgz && tar zxvf rsc-linux-amd64.tgz -C tmp;mv tmp/rsc/rsc . && chmod +x ./rsc && ./rsc --version 
script:
- bundle exec danger --verbose
