language: ruby
cache:
  directories:
  - bundle
rvm:
- 2.4.1
bundler_args: "--without documentation --path bundle"
before_install:
- git fetch --depth=1
- gem install bundler
- mkdir -p tmp && wget --no-check-certificate https://binaries.rightscale.com/rsbin/rsc/v8/rsc-linux-amd64.tgz
  && tar zxvf rsc-linux-amd64.tgz -C tmp;mv tmp/rsc/rsc . && chmod +x ./rsc && ./rsc
  --version
- sudo apt-get install nodejs -y
- curl -L https://www.npmjs.com/install.sh | sh
- npm install

script:
- bundle exec danger --verbose
- bundle exec danger plugins lint --verbose

deploy:
# generate the active plugin list json file
- provider: script
  script: bundle exec rake generate_plugin_list
# upload the active plugin list json file to s3
- provider: s3
  bucket: rs-policysync-tool
  region: us-east-1
  skip_cleanup: true
  local_dir: "$TRAVIS_BUILD_DIR/$WORK_DIR/dist"
  acl: public_read
  access_key_id: "$PLUGIN_SYNC_TOOL_S3_AWS_ACCESS_KEY_ID"
  secret_access_key: "$PLUGIN_SYNC_TOOL_S3_AWS_SECRET_ACCESS_KEY"
  on:
    branch: master
env:
  global:
  - secure: OGBXrntqRfNflrFc/+24OwxwRLwCoAc/qveK3UmM+/YUr2zdEJrBuA0tdyTAlvGWlejvCKHWP1yg9J8tklB437GhTziCvuO0AhFpwsJjNGkfkwyqhN9rN/TyKqQ4Rdkxt/PVjurj9TJz5ATVIY9i9gYjmw2+r4soP1ArSwOcIH7uw/edJLDfeu+SWTSPUUr2XaUnxQDTfB848FN14B7b52oDN22qxNHvV45ukyAlUOLoNoGS2KGdemXVXw+6N+BSGYpJ6S1yTuaRNhbFqAwtG3sKrAD6fdKd0GVy5i9WDAPZ65VvesSbjewiD6F/M91ri68AUUT1QKA1Nj4deL56v2pASg8DeXLFCOwhFAEE5DAcJJhmlPf6DqQ+hKsgSE6o/1g7HbfdM//pmK+rczxyEsqBgRJSAS+oljSen92UPfZt2QR6LsTZAFBI17xlKsX+uABlG239yfx7NDIMbS/cy0V/6ukLXtETb9lqrRoT+/HrZWO5XKfBpqsL3f+tUTeb70sW48+XGdk4mmmeAxYjeW5VuS803bXQIRMBz7T3srSynu/hG8mqaOcx+ehWgM+Fm+Z2bPQjIFXDt9L62jDGxk2L7RVpWp9WfYfvhNywI+cBCF2z4cszU6ypVKRsymdCvsqKFnmaFRPz4jKye7X7c1FIqc6iO9FsS1i8gfTC7Tk=
