name: Test Plugins

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  plugin_test:
    name: "plugin Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100 # https://github.com/danger/danger/issues/913
      - run: |
          mkdir -p tmp && wget --no-check-certificate https://binaries.rightscale.com/rsbin/rsc/v8/rsc-linux-amd64.tgz && tar zxvf rsc-linux-amd64.tgz -C tmp;mv tmp/rsc/rsc . && chmod +x ./rsc
          ./rsc --version
      - uses: ruby/setup-ruby@v1
        with:
          # ruby-version: 2.4.1 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run Tests
        shell: bash -l {0} # https://github.com/actions/virtual-environments/issues/4
        run: |
          nvm install
          nvm use
          npm install
          bundle install --without documentation --path bundle
          bundle exec danger --verbose
          ./node_modules/.bin/markdownlint-cli2 "**/*.md" "#node_modules" "#bundle" "#vendor"
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
